# Dockerfile
FROM public.ecr.aws/lambda/python:3.9

ADD requirements.txt .
COPY ./docker/. ${LAMBDA_TASK_ROOT}
ADD ./src/. ${LAMBDA_TASK_ROOT}/
ADD ./assets/.  ${LAMBDA_TASK_ROOT}/

RUN pip install -r requirements.txt
